export const GET_WORK_LIST = 'GET_WORK_LIST'

export const UPDATE_WORK_LIST = 'UPDATE_WORK_LIST'

export const GET_BASE_SETTING = 'GET_BASE_SETTING'

export const UPDATE_BASE_SETTING = 'UPDATE_BASE_SETTING'
