export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST'

export const UPDATE_ARTICLE_LIST = 'UPDATE_ARTICLE_LIST'

export const GET_BASE_SETTING = 'GET_BASE_SETTING'

export const UPDATE_BASE_SETTING = 'UPDATE_BASE_SETTING'
